anggota/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index')
]

bank_mitra/urls.py
from django.urls import path
from .views import index, add_mitra

app_name = "bank"

urlpatterns = [
    path('', index, name='index'),
    path('add', add_mitra, name="add")
]

login/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index')
]

myWebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from .views import home, log_out

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('anggota/', include('anggota.urls')),
    path('login/', include('login.urls')),
    path('bank-mitra/', include('bank_mitra.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('produk/', include('produk.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('logout/', log_out)
]

pesanan/urls.py
from django.urls import path
from .views import index, pk_pinjam, pk_baca, p_menu

urlpatterns = [
    path('', index, name='index'),
    path('pinjam/', pk_pinjam, name='pinjam'),
    path('baca/', pk_baca, name='baca'),
    path('menu/', p_menu, name='menu')
]

produk/urls.py
from django.urls import path
from .views import index, komik, menu

urlpatterns = [
    path('', index, name='index'),
    path('komik/', komik, name='komik'),
    path('menu/', menu, name='menu')
]

transaksi/urls.py
from django.urls import path
from .views import index, tp_pinjam, tp_baca

urlpatterns = [
    path('', index, name='index'),
    path('pinjam/', tp_pinjam, name='pinjam'),
    path('baca/', tp_baca, name='baca')
]

anggota/models.py
from django.db import models

# Create your models here.

bank_mitra/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

pesanan/models.py
from django.db import models

# Create your models here.

produk/models.py
from django.db import models

# Create your models here.

transaksi/models.py
from django.db import models

# Create your models here.

myWebsite/forms.py
from django import forms

class LoginForm(forms.Form):
    nomor_anggota = forms.CharField(label='Nomor Anggota', max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

anggota/views.py
from django.shortcuts import render
from myWebsite.views import get_data


def index(request):
    map = get_data("anggota")
    return render(request, "anggota.html", {'db': map})

bank_mitra/views.py
from django.shortcuts import render, redirect
from myWebsite.views import get_data, dictfetchall
from django.db import connection

def index(request):
    map = get_data("bank_mitra")
    return render(request, "bank_mitra.html", {'db': map})

def add_mitra(request):
    if request.method == "POST":
        print(request.POST["mitra"])
        with connection.cursor() as cursor:
            cursor.execute("set search_path to komika")
            cursor.execute("select count(*) from bank_mitra")
            map = dictfetchall(cursor)
            count = map[0]['count'] + 1
            strcount = str(count)
            lenstr = 4-len(strcount)
            id_bank = 'B' + ('0'*lenstr) + strcount
            cursor.execute("insert into bank_mitra values (%s, %s)" , [id_bank, request.POST["mitra"]])
    return redirect("bank:index")

login/views.py
from django.shortcuts import render

def index(request):
    return render(request, "login.html")

myWebsite/views.py
from django.shortcuts import render
from django.db import connection
from myWebsite.forms import LoginForm
from django.http import HttpResponseRedirect

def home(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        error_message = ''
        if form.is_valid() :
            data = form.cleaned_data
            no_anggota = data['nomor_anggota']
            password = data['password']
            with connection.cursor() as cursor:
                cursor.execute("set search_path to komika")
                cursor.execute("select nama, password from anggota where no_anggota = '%s'" % no_anggota)
                map = dictfetchall(cursor)
            if password == map[0]['password'] :
                request.session["nomor_anggota"] = no_anggota
                request.session["nama"] = map[0]['nama']
            else :
                error_message = 'Wrong Password'
            return render(request, "homepage.html", {'form' : form, 'message' : error_message})
    else:
        form = LoginForm()
    return render(request, "homepage.html", {'form' : form})

def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def get_data(table):
    with connection.cursor() as cursor:
        cursor.execute("set search_path to komika")
        cursor.execute("select * from %s" % table)
        map = dictfetchall(cursor)
    return map

def log_out(request):
    request.session.flush()
    return HttpResponseRedirect("/")

pesanan/views.py
from django.shortcuts import render
from myWebsite.views import get_data

def index(request):
    map = get_data("pesanan_komik_pinjam")
    return render(request, "pk_pinjam.html", {'db': map})

def pk_pinjam(request):
    map = get_data("pesanan_komik_pinjam")
    return render(request, "pk_pinjam.html", {'db': map})

def pk_baca(request):
    map = get_data("pesanan_komik_baca")
    return render(request, "pk_baca.html", {'db': map})

def p_menu(request):
    map_pinjam = get_data("pesanan_menu_trpinjam")
    map_baca = get_data("pesanan_menu_trbaca")
    return render(request, "p_menu.html", {'db_pinjam': map_pinjam, 'db_baca' : map_baca})

produk/views.py
from django.shortcuts import render
from myWebsite.views import get_data, dictfetchall
from django.db import connection

def index(request):
    map = get_data("produk")
    return render(request, "produk.html", {'db': map})

def komik(request):
    with connection.cursor() as cursor:
        cursor.execute("set search_path to komika")
        cursor.execute("select p.id_produk, p.nama, p.jumlah, k.jumlah_available, k.seri from produk p join komik k on p.id_produk = k.id_produk")
        map = dictfetchall(cursor)
    return render(request, "komik.html", {'db': map})

def menu(request):
    with connection.cursor() as cursor:
        cursor.execute("set search_path to komika")
        cursor.execute("select p.id_produk, p.nama, m.harga, p.jumlah from produk p join menu m on p.id_produk = m.id_produk")
        map = dictfetchall(cursor)
    return render(request, "menu.html", {'db': map})

transaksi/views.py
from django.shortcuts import render
from myWebsite.views import get_data

def index(request):
    map = get_data("transaksi_pinjam")
    return render(request, "tp_pinjam.html", {'db': map})

def tp_pinjam(request):
    map = get_data("transaksi_pinjam")
    return render(request, "tp_pinjam.html", {'db': map})

def tp_baca(request):
    map = get_data("transaksi_baca")
    return render(request, "tp_baca.html", {'db': map})

templates/anggota.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
            <th scope="col">No.Anggota</th>
            <th scope="col">ID</th>
            <th scope="col">Nama</th>
            <th scope="col">Alamat</th>
            <th scope="col">Tanggal Lahir</th>
            <th scope="col">No.Hp</th>
            <th scope="col">Tanggal Keanggotaan</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.no_anggota }}</td>
            <td>{{ data.id }}</td>
            <td>{{ data.nama }}</td>
            <td>{{ data.alamat }}</td>
            <td>{{ data.tanggal_lahir }}</td>
            <td>{{ data.no_hp }}</td>
            <td>-</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/bank_mitra.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
        <div>
            <form class="bank-form" method="POST" action="{% url 'bank:add' %}">
                {% csrf_token %}
                <input type="text" name="mitra" placeholder="Nama Bank">
                <button type="submit">Add Bank Mitra</button>
            </form>
        </div>
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                <th scope="col">Kode</th>
                <th scope="col">Nama Bank</th>
                </tr>
            </thead>
            <tbody>
                {% for data in db %}
                <tr>
                <th scope="row">{{ data.kode }}</td>
                <td>{{ data.nama }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homepage.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Arvo&display=swap" rel="stylesheet">
    <title>KOMIKA</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
        <a class="navbar-brand" href="#">KOMIKA</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if request.session.nomor_anggota != None %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="/login/">Login</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link" href="/anggota/">Anggota</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/bank-mitra/">Bank Mitra</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Produk
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/produk/komik/">Komik</a>
                <a class="dropdown-item" href="/produk/menu/">FnB</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Transaksi
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/transaksi/pinjam/">Pinjam</a>
                <a class="dropdown-item" href="/transaksi/baca/">Baca</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/pesanan/pinjam/">Pinjam</a>
                  <a class="dropdown-item" href="/pesanan/baca/">Baca</a>
                  <a class="dropdown-item" href="/pesanan/menu/">Menu</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout/">Logout</a>
            </li>
          </ul>
          <a class="navbar-brand" href="#">{{ request.session.nama }}</a>
          {% endif %}
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

templates/homepage.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="big-box">
    <h1 class="home-title">KOMIKA</h1>
    {% if request.session.nomor_anggota == None %}
    <form class="login-form" action="" class="" method="POST">
        {% csrf_token %}
        <p>{{ error_message }}</p>
        <input type="input" class="form-control mr-sm-2" name="nomor_anggota" id="inputEmail" placeholder="Nomor Anggota" required >
        <input type="password" class="form-control mr-sm-2" name="password" id="inputPass" placeholder="Password" required>
        <button type="submit" style="opacity: 1 !important;">Login</button>
    </form>
    {% endif %}
</div>

{% endblock %}

templates/komik.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">ID Produk</th>
            <th scope="col">Nama</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Ketersediaan</th>
            <th scope="col">Seri</th>
            <th scope="col">Harga</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.id_produk }}</td>
            <td>{{ data.nama }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.jumlah_available }}</td>
            <td>{{ data.seri }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="big-box">
    <h1>Login :)</h1>
</div>

{% endblock %}

templates/menu.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">ID Produk</th>
            <th scope="col">Nama</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Harga</th>
            <!-- <th scope="col">Ketersediaan</th>
            <th scope="col">Seri</th>
            <th scope="col">Harga</th> -->
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.id_produk }}</td>
            <td>{{ data.nama }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.harga }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/p_menu.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">Nomor Urut</th>
            <th scope="col">Jumlah Komik</th>
            <th scope="col">ID Menu</th>
            <th scope="col">Timestamp Transaksi</th>
            <th scope="col">Nomor Anggota</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db_pinjam %}
            <tr>
            <th scope="row">{{ data.nomor_urut }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.id_produk }}</td>
            <td>{{ data.timestamp_pinjam }}</td>
            <td>{{ data.no_anggota }}</td>
            </tr>
            {% endfor %}
            {% for data in db_baca %}
            <tr>
            <th scope="row">{{ data.nomor_urut }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.id_produk }}</td>
            <td>{{ data.timestamp_baca }}</td>
            <td>{{ data.no_anggota }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/pesanan.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="big-box">
    <h1>Pesanan :)</h1>
</div>

{% endblock %}

templates/pk_baca.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">Nomor Urut</th>
            <th scope="col">Jumlah Komik</th>
            <th scope="col">Status</th>
            <th scope="col">ID Komik</th>
            <th scope="col">Timestamp Transaksi</th>
            <th scope="col">Nomor Anggota</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.nomor_urut }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.status }}</td>
            <td>{{ data.id_produk }}</td>
            <td>{{ data.timestamp_baca }}</td>
            <td>{{ data.no_anggota }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/pk_pinjam.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">Nomor Urut</th>
            <th scope="col">Jumlah Komik</th>
            <th scope="col">Status</th>
            <th scope="col">ID Komik</th>
            <th scope="col">Timestamp Transaksi</th>
            <th scope="col">Nomor Anggota</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.nomor_urut }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.status }}</td>
            <td>{{ data.id_produk }}</td>
            <td>{{ data.timestamp_pinjam }}</td>
            <td>{{ data.no_anggota }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/produk.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">ID Produk</th>
            <th scope="col">Nama</th>
            <th scope="col">Jumlah</th>
            <th scope="col">Tipe Produk</th>
            <!-- <th scope="col">Ketersediaan</th>
            <th scope="col">Seri</th>
            <th scope="col">Harga</th> -->
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.id_produk }}</td>
            <td>{{ data.nama }}</td>
            <td>{{ data.jumlah }}</td>
            <td>{{ data.tipe_produk }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/tp_baca.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">Timestamp</th>
            <th scope="col">Jumlah Komik</th>
            <th scope="col">Jumlah Menu</th>
            <th scope="col">Total Biaya</th>
            <th scope="col">Nomor Anggota</th>
            <th scope="col">Kode Pembayaran Bank</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.timestamp }}</td>
            <td>{{ data.jumlah_komik }}</td>
            <td>{{ data.jumlah_menu }}</td>
            <td>{{ data.total_biaya }}</td>
            <td>{{ data.no_anggota }}</td>
            <td>{{ data.kode }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/tp_pinjam.html
{% extends 'base.html' %} 
{% block content %}
{% load static %}

<div class="container">
    <table class="table table-hover table-responsive-md">
        <thead>
            <tr>
            <th scope="col">Timestamp</th>
            <th scope="col">Jumlah Komik</th>
            <th scope="col">Jumlah Menu</th>
            <th scope="col">Total Biaya</th>
            <th scope="col">Denda</th>
            <th scope="col">Durasi</th>
            <th scope="col">Tanggal Pinjam</th>
            <th scope="col">Tanggal Kembali</th>
            <th scope="col">Tanggal Dikembalikan</th>
            <th scope="col">Nomor Anggota</th>
            <th scope="col">Kode Pembayaran Bank</th>
            </tr>
        </thead>
        <tbody>
            {% for data in db %}
            <tr>
            <th scope="row">{{ data.timestamp }}</td>
            <td>{{ data.jumlah_komik }}</td>
            <td>{{ data.jumlah_menu }}</td>
            <td>{{ data.total_biaya }}</td>
            <td>{{ data.denda }}</td>
            <td>{{ data.durasi_pinjam }}</td>
            <td>{{ data.tanggal_pinjam }}</td>
            <td>{{ data.tanggal_kembali }}</td>
            <td>{{ data.tanggal_dikembalikan }}</td>
            <td>{{ data.no_anggota }}</td>
            <td>{{ data.kode }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}